### ISSUE TITLE
Force miui launcher recents task in 3rd party launcher a10

### ISSUE THREAD

**Issue by Yet-another-NPC-guy** [HCGStudio/FuckMIUIGesture#2]
Please add support to force use of miui launcher recents task in 3rd party launcher a10, system ui recents doesn't work fine in miui 12.5 A10.

If you can and want

**Comment by mahoshojoHCG** [comment]
I don't have miui12.5 or A10 MIUI devices, you can try using quick switch to set lawnchair as recent provider.

**Comment by ZoomZero** [comment]
Hello. How to ur use module?
